### ISSUE TITLE
DOMParser is not defined

### ISSUE THREAD

**Issue by Simply007** [kontent-ai/rich-text-resolver-js#16]
### Brief bug description

Tree shaking is not applied in the case of `@kontent-ai\rich-text-resolver\dist\cjs\src\parser\browser\rich-text-browser-parser.js`. 

### Repro steps

https://github.com/kontent-ai/gatsby-packages/pull/236/files#diff-8fff385791166d8060e27ff7becf1ea3c8193ee0b83a480c5e77b0c385e5a686R99-R113

**Comment by pokornyd** [comment]
fixed as a part of #17
