### ISSUE TITLE
Define data contract for Vue serializers

### ISSUE THREAD

**Issue by pokornyd** [kontent-ai/rich-text-resolver-js#23]
### Motivation

[Vue resolution package](https://github.com/rdunk/sanity-blocks-vue-component) does not export a data contract for serializers, forcing the type `any`.

### Proposed solution

Define a suitable data contract for serializers and export it in the base package.

**Comment by Simply007** [comment]
See https://github.com/kontent-ai/sample-app-vue/pull/124/files#diff-22f2eb730ddfb6b7569d040d694364aaffddf33d6b1c88880293aaca48edd3feR24

**Comment by pokornyd** [comment]
https://github.com/portabletext/vue-portabletext this is the new package that should be used.
