### ISSUE TITLE
Transforming complex RTE HTML fails 

### ISSUE THREAD

**Issue by milan009** [kontent-ai/rich-text-resolver-js#32]
### Brief bug description

I've setup a RTE with a lot of overlapping styles, lists and a table with images and lists. I took the HTML from deliver and attempted to resolve it into portable text, but the resolver crashed. Parsing into json tree seems to work fine. 

```
node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transformer\portable-text-transf
ormer.js:195
    const numCols = tableRow.children.length;
                                      ^

TypeError: Cannot read properties of undefined (reading 'length')
    at transformTable (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transform
er\portable-text-transformer.js:195:39)
    at transformElement (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transfo
rmer\portable-text-transformer.js:147:12)
    at transformNode (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transforme
r\portable-text-transformer.js:142:16)
    at Array.<anonymous> (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transf
ormer\portable-text-transformer.js:131:33)
    at Array.flatMap (<anonymous>)
    at flatten (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transformer\port
able-text-transformer.js:110:18)
    at Object.transformToPortableText (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portabl
e-text-transformer\portable-text-transformer.js:14:23)
    at Object.<anonymous> (...\portable-text-experiment\index.js:13:31)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
```

Even after removing the table from the HTML, I got a different error

```
node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transformer\portable-text-transf
ormer.js:70
            previousBlock.children.push(item);
                                   ^

TypeError: Cannot read properties of undefined (reading 'push')
    at (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-transformer\portable-text
-transformer.js:70:36
    at Array.reduce (<anonymous>)
    at mergeBlocksAndSpans (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portable-text-tran
sformer\portable-text-transformer.js:67:38)
    at ...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\utils\transformer-utils.js:122:129
    at ...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\utils\transformer-utils.js:122:112
    at Object.transformToPortableText (...\portable-text-experiment\node_modules\@kontent-ai\rich-text-resolver\dist\cjs\src\transformers\portabl
e-text-transformer\portable-text-transformer.js:15:12)
    at Object.<anonymous> (...\portable-text-experiment\index.js:13:31)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)

```

### Repro steps

Try to transform following HTML into portable text in node.

`"<p>Text</p>\n<p><strong>Bold text</strong></p>\n<p><strong>Bold text </strong><em><strong>with itallic</strong></em><strong> in it</strong></p>\n<p><strong>Overlapping bold </strong><em><strong>over</strong></em><em> itallic text</em></p>\n<ol>\n  <li>Odered list</li>\n  <li>Ord<strong>ered </strong><strong><sub>li</sub></strong><a href=\"http://www.example.com\"><em><strong><sub>s</sub></strong></em><em>t with s</em>tyles and li</a>nk\n    <ol>\n      <li>Nested ordered list</li>\n      <li>Nested ordered list\n        <ol>\n          <li>More nested ordered list</li>\n          <li><br></li>\n        </ol>\n      </li>\n    </ol>\n  </li>\n</ol>\n<h1><br></h1>\n<figure data-asset-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\" data-image-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\"><img src=\"https://example.com/image.png\" data-asset-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\" data-image-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\" alt=\"\"></figure>\n<h1>Heading</h1>\n<h4>Heading little</h4>\n<table><tbody>\n  <tr><td>1</td><td>2 - w<strong>ith bold te</strong>xt</td><td>3 - w<a href=\"http://www.example.com\">ith link ins</a>ide</td></tr>\n  <tr><td>4 <em>- w</em><a data-item-id=\"6538fde0-e6e5-425c-8642-278e637b2dc1\" href=\"\"><em>ith lin</em>k to cont</a>ent</td><td><p>5 - with image in <em>table</em></p>\n<figure data-asset-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\" data-image-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\"><img src=\"https://example.com/image.png\" data-asset-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\" data-image-id=\"8c35b61a-8fcb-4089-a576-5a5e7a158bf2\" alt=\"\"></figure>\n<p><em>and style over the i</em>mage</p>\n</td><td><p>6 - with list&nbsp;</p>\n<ul>\n  <li>List in table</li>\n  <li>Another list item in table\n    <ul>\n      <li>Nested in table\n        <ul>\n          <li>More nested in table&nbsp;\n            <ol>\n              <li>Ordered inside unorederd</li>\n              <li>More unordered</li>\n            </ol>\n          </li>\n        </ul>\n      </li>\n    </ul>\n    <ol>\n      <li>Returning byck</li>\n    </ol>\n  </li>\n</ul>\n<ol>\n  <li><br></li>\n</ol>\n</td></tr>\n  <tr><td>7</td><td>8</td><td>9</td></tr>\n</tbody></table>"`
            

### Expected behavior

Transform into portable text without crash

### Test environment

 - node 20.0
 - Version 0.0.4

**Comment by milan009** [comment]
A RTE with 20x20 table seems to fail as well 

`<table><tbody>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n  <tr><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td><td><br></td></tr>\n</tbody></table>`

**Comment by Simply007** [comment]
I tested out parsing using both node and browser parser and it worked fine locally: #33

**Comment by milan009** [comment]
The resolver works correctly, the issue was caused by incorrectly escaped characters in data I used for testing `\n -> \\n`
