### ISSUE TITLE
Issue with the Rich text resolver output interrupted by line breaks

### ISSUE THREAD

**Issue by keerthiga-64** [kontent-ai/rich-text-resolver-js#56]
### Brief bug description

- There is currently a problem with the output of bold type text that is interrupted by line breaks within a rich text component in Kontent.ai.

- Specifically, it seems like the mark type (Italics,bold,etc…) is getting applied only  to the first element and not to subsequent elements when using Shift+Enter for line breaks.

### What went wrong?
It was working long back but now it does not seems to work, output isn’t returning the strong value for the second element
### Repro steps

1. Go to 'Rich text component'
2. Give any text and then give ctrl+enter or shift +enter for line break and provide the second element ,and then select these elements together and apply bold or italics.
3. Then the bold/italics format will only be added to the first element in UI and the changes will not get reflected for the second element.
4. See error in below screenshot

### Expected behavior

The mark type (Italics,bold,etc…) should get applied to both the first element and also to the subsequent elements in UI when using Shift+Enter for line breaks.
### Test environment

 - Browser [chrome]
 - Version [129.0]

### Screenshots
<img width="692" alt="image" src="https://github.com/user-attachments/assets/5ffd2ba2-9cb0-4d8b-90e3-ccacd43459e2">

<img width="688" alt="image" src="https://github.com/user-attachments/assets/35404d97-9324-4ff2-a015-9e6b6061ae77">

**Comment by pokornyd** [comment]
Hello and thank you for your submission. I'll try to reproduce the problem and will update you on the resolution or if I need any further context, thanks for your patience!
